var bicycleArr = [
    {
        id:0,
        name:"AZIMUT",
        type:"SPORT",
        color:"BLUE",
        wheel_size:30,
        price:45.25,
        description:"none",
        status:'Available'
    },
    {
        id:1,
        name:"FURY",
        type:"DITRBIKE",
        color:"BLACK",
        wheel_size:30,
        price:52.50,
        description:"none",
        status:'Available'
    },
    {
        id:2,
        name:"HARLEY",
        type:"CLASSIC",
        color:"METALIC",
        wheel_size:25,
        price:68.99,
        description:"none",
        status:'Busy'
    },
    {
        id:3,
        name:"OSCAR",
        type:"SPORT",
        color:"ORANGE",
        wheel_size:28.3,
        price:55.25,
        description:"none",
        status:'Busy'
    },
    {
        id:4,
        name:"EL DIABLO",
        type:"SPORT",
        color:"RED",
        wheel_size:26.7,
        price:55.38,
        description:"none",
        status:'Unavailable'
    }
]
export default bicycleArr